server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wx_erp?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  database-validation-mode: ERROR
  show-sql: true
  language: kotlin
